---
- name: Include common role
  ansible.builtin.import_role:
    name: Common

# prereqs
# TODO split this out based on platform
- name: Install packages (ubuntu/debian)
  ansible.builtin.apt:
    pkg:
      - python3-virtualenv
      - git

- name: Create directory structure
  ansible.builtin.file:
    state: directory
    path: "{{ item }}"
    owner: "{{ common.user_config.username }}"
    group: "{{ common.user_config.group }}"
  loop:
    - "{{ common.base_dir }}"
    - "{{ common.base_dir }}/moonraker"
    - "{{ common.base_dir }}/data"

- name: Clone moonraker repo
  ansible.builtin.git:
    repo: "{{ repo_path }}"
    dest: "{{ common.base_dir }}/moonraker/repo"
    update: true
  become: true
  become_user: "{{ user_config.username }}"

- name: Create virtualenv
  ansible.builtin.pip:
    virtualenv: "{{ common.base_dir }}/moonraker/venv"
    requirements: "{{ common.base_dir }}/moonraker/repo/scripts/moonraker-requirements.txt"
  become: true
  become_user: "{{ common.user_config.username }}"

- name: Create systemd unit file
  ansible.builtin.template:
    src: moonraker.service.j2
    dest: /etc/systemd/system/moonraker.service
  notify: restart moonraker

- name: Enable systemd unit
  ansible.builtin.systemd:
    daemon_reload: true
    enabled: true
    state: started
    name: moonraker.service
  notify: restart moonraker

- name: Setup logrotate
  ansible.builtin.include_role:
    name: Common
    tasks_from: logrotate

- name: Configure moonraker
  ansible.builtin.template:
    src: moonraker.conf.j2
    dest: "{{ moonraker.config_file }}"
    owner: "{{ common.user_config.username }}"
    group: "{{ common.user_config.group }}"
  notify: restart moonraker
