---
- name: Install logrotate
  ansible.builtin.apt:
    pkg:
      - logrotate

- name: Setup logrotate
  ansible.builtin.template:
    src: logrotate.j2
    dest: /etc/logrotate.d/{{ log_config.name }}
    mode: "644"
  when: "log_config.name"
