---
- name: Include common role
  ansible.builtin.import_role:
    name: common

# prereqs
# https://github.com/Klipper3d/klipper/blob/master/scripts/install-octopi.sh
# TODO split this out based on platform
- name: Install packages (ubuntu/debian)
  ansible.builtin.apt:
    pkg:
      - build-essential
      - python3-virtualenv
      - python3-dev
      - libffi-dev
      - libncurses-dev
      - git

- name: Create directory structure
  ansible.builtin.file:
    state: directory
    path: "{{ item }}"
    owner: "{{ common.user_config.username }}"
    group: "{{ common.user_config.group }}"
  loop:
    - "{{ common.base_dir }}"
    - "{{ common.base_dir }}/klipper"
    - "{{ common.base_dir }}/config"

- name: Clone klipper repo
  ansible.builtin.git:
    repo: "{{ repo_path }}"
    dest: "{{ common.base_dir }}/klipper/repo"
    update: true
  become: true
  become_user: "{{ common.user_config.username }}"

- name: Create virtualenv
  ansible.builtin.pip:
    virtualenv: "{{ common.base_dir }}/klipper/venv"
    requirements: "{{ common.base_dir }}/klipper/repo/scripts/klippy-requirements.txt"
  become: true
  become_user: "{{ common.user_config.username }}"

- name: Create systemd unit file
  ansible.builtin.template:
    src: klipper.service.j2
    dest: /etc/systemd/system/klipper.service
  notify: restart klipper

- name: Enable systemd unit
  ansible.builtin.systemd:
    daemon_reload: true
    enabled: true
    name: klipper.service
  notify: restart klipper
# TODO configure virtual_sdcard path

- name: Setup logrotate
  ansible.builtin.include_role:
    name: common
    tasks_from: logrotate
